## User Login [POST /login]

Logs a user in to the API

Scope: public

+ Request (application/json)
  + Attributes
    + email: `surly.badger@fuelrats.com` (string, required) - The email of the user
    + password: `P455w0rd` (string, required) - The password of the user

+ Response 201 (application/json)
  + Attributes
    + links (Link) - Links
    + data (User) - Information about the user
