secrets:
  frapi_postgres_password:
    file: .docker/secrets/frapi_postgres_password
  frapi_cookie:
    file: .docker/secrets/frapi_cookie
  frapi_jwt_secret:
    file: .docker/secrets/frapi_jwt_secret

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: fuelrats
      POSTGRES_PASSWORD_FILE: /run/secrets/frapi_postgres_password
      POSTGRES_DB: fuelrats
    secrets:
      - frapi_postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fuelrats"]
      interval: 2s
      timeout: 5s
      retries: 10

  api:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      FRAPI_HOSTNAME: "0.0.0.0"
      FRAPI_PORT: "8080"
      FRAPI_URL: "http://localhost:8080"
      FRAPI_POSTGRES_HOSTNAME: db
      FRAPI_POSTGRES_PORT: "5432"
      FRAPI_POSTGRES_DATABASE: fuelrats
      FRAPI_POSTGRES_USERNAME: fuelrats
      FRAPI_POSTGRES_PASSWORD_FILE: /run/secrets/frapi_postgres_password
      FRAPI_FRONTEND_URL: "http://localhost:3000"
      FRAPI_GEOIP_DIRECTORY: /app/geoip
    secrets:
      - frapi_cookie
      - frapi_jwt_secret
      - frapi_postgres_password
    ports:
      - "8080:8080"

volumes:
  pgdata:
