FORMAT: 1A
HOST: http://api.fuelrats.com

# Fuel Rats API

This is the Fuel Rats API

::: warning
The API is currently under development so this document is subject to change at short notice.
:::

<!-- include(rescues.apib) -->
