<!-- include(models.apib) -->

# Group Rescues

<!-- include(rescues/list.apib) -->

<!-- include(rescues/create.apib) -->

<!-- include(rescues/retrieve.apib) -->

<!-- include(rescues/update.apib) -->
