## Meta (object)
+ count: `25` (number) - Number of results returned
+ limit: `25` (number) - Maximum results returned per request
+ offset: `0` (number) - The offset of the current results from the top index of the database
+ total: `3484` (number) - The total number of results in the database
