## Rat (object)
+ id: `56a8c2bc9b884b56e9cfe8ba` (string) - The ID for this rat
+ archive: `false` (boolean) - This rat is archived
+ CMDRname: `Trezy` (string, required) - The in-game username of this rat
+ createdAt: `2015-07-15T22:00:00.000Z` (string, required) - The timestamp for when this entry was created
+ drilled: (Drilled) - This rat's drill status
+ gamertag: `Trezy` (string) - This rat's Xbox gamertag
+ lastModified: `2016-01-26T20:22:47.643Z` (string, required) - The timestamp for when this entry was last modified
+ joined: `2015-07-15T22:00:00.000Z` (string, required) - The timestamp for when this rat joined the fuel rats
+ nicknames: `Trezy` (array[string], required) - The nicknames this rat uses on the IRC
+ platform: `pc` (string, required) - The platform this rat is on
+ rescues: `56a78141f9fbac397a27ab3e` (array[string]) - A list of IDs all rescues that have been performed by this rat
+ user: (User, required) - The user associated with this user.

## Drilled (object)
+ dispatch: `false` (boolean) - This rat is drilled as a dispatch
+ rescue: `false` (boolean) - This rat is drilled for rescueing
