<!doctype html>
<head>
  <link rel="stylesheet" href="/style.min.css">
  {% block head %}
  {% endblock %}
</head>
<body style="margin: 0">
  {% block body %}
  <header id="masthead" class="site-header fixed float-header" role="banner">
    <div class="header-wrap">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-8 col-xs-12">
            <a href="https://www.fuelrats.com/" title="The Rat Cave"><img class="site-logo" src="http://fuelrats.com/wp-content/uploads/2015/07/fuelrats_tee_logo-smallish.png" alt="The Rat Cave"></a>
          </div>
          <div class="col-md-8 col-sm-4 col-xs-12">
          <div class="btn-menu"></div>
          <nav id="mainnav" class="mainnav" role="navigation">
            <div class="menu-main-menu-container"><ul id="menu-main-menu" class="menu"><li id="menu-item-235" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-235"><a href="http://fuelrats.com#Rescues">Rescues</a></li>
              <li id="menu-item-1219" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1219"><a href="https://www.fuelrats.com/community/">Community Hub</a></li>
              <li id="menu-item-1318" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1318"><a href="https://www.fuelrats.com/fuelrat-events/">Events</a></li>
              <li id="menu-item-1578" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1578"><a href="https://www.fuelrats.com/leaderboard/">Leaderboard</a></li>
              <li id="menu-item-960" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-960"><a href="https://www.fuelrats.com/loot/">Loot</a></li>
              <li id="menu-item-239" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-239"><a href="http://fuelrats.com#Propaganda">Propaganda</a></li>
              <li id="menu-item-409" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-409"><a href="http://fuelrats.com#Links">Links</a></li>
              <li id="menu-item-240" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-240"><a href="http://fuelrats.com#About">About</a></li>
              <li id="menu-item-1970" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1970"><a href="http://www.fuelrats.com/rats-honors/">Fuel Rats Honor Badges</a></li>
              <li id="menu-item-2497" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2497"><a href="https://www.fuelrats.com/join/">Become a Rat</a></li>
              <li id="menu-item-1971" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1971"><a href="http://www.fuelrats.com/tfrm/">Minor Faction</a></li>
              <li id="menu-item-1448" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1448"><a href="https://www.fuelrats.com/register/">Login / Register</a></li>
            </ul></div>
          </nav>
          </div>
        </div>
      </div>
    </div>
</header>
  {% endblock %}

  {% block resources %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js"></script>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>

  <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.1/moment.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>

  {% endblock %}
</body>
