## Create a rescue [POST /rescues]

Create a new active Rescue

Scope: public

+ Request (application/json)
  + Attributes
    + nickname: `Trezy` (string, required) - The IRC nickname of the client
    + CMDRname: `Trezy` (string, required) - The in-game username of the client
    + codeRed: `false` (boolean) - Whether this rescue is a code-red/case-red situation.

+ Response 201 (application/json)
  + Attributes
    + links (Link) - Links
    + data (Rescue) - The rescue that was just created
