## Get a list of rescues [GET /rescues]

Retrieves a list of any existing rescues and all associated information

Scope: public

+ Response 200 (application/json)
  + Attributes
    + links (Link) - Links
    + meta (Meta) - Statistics on the current result
    + data (array[Rescue]) - A list of rescues
