## User (object)
+ email: `john@smith.com` (string, required) - The email address of this user
+ password: `6b1b36cbb04b41490bfc0ab2bfa26f86` (string, required) - The password of this user
+ CMDRs: `Trezy` ([Rat], required) - The rats registered under this user
