## Create a rat [POST /api/rats]

Create a new rat

Scope: public

+ Request (application/json)
    + Attributes
      + nicknames: `Trezy` (array[string], required) - The IRC nicknames of the rat
      + CMDRname: `Trezy` (string, required) - The in-game username of the rat

+ Response 201 (application/json)
    + Attributes
      + links (Link) - Links
      + data (Rat) - The rat that was just created
