## Retrieve a single rat [GET /api/rats/{id}/]

Retrieve a single rescue by its ID

::: warning
This API is not yet implemented. See [Get rat by ID API endpoint not implemented. #29](https://github.com/FuelRats/api.fuelrats.com/issues/29) for progress
:::

Scope: public

+ Parameters
  + id: `56a78141f9fbac397a27ab3e` (integer, required) - ID of the rat to retrieve information on

+ Response 200 (application/json)
    + Attributes
        + links: (Link) - Links
        + data: (object, nullable) - Not yet implemented
