export { default } from './Document'
export * from './Document'
export { default as DatabaseDocument } from './DatabaseDocument'
export { default as ObjectDocument } from './ObjectDocument'
export { default as ErrorDocument } from './ErrorDocument'
